name: ship-check-be-action
on:
  push:
    branches:
      - release

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: dependencies
        run: npm install

      - name: test
        run: npm test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: dependencies
        run: npm install

      - name: build
        run: npm run build

      - name: zip 
        run: zip -q -r dist.zip dist/

      - name: upload zip to actions artifact
        uses: actions/upload-artifact@v4
        with:
          name: ship-check-be
          path: dist.zip
          retention-days: 1
  
  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
    
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: ship-check-be

      - name: upload to s3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws s3 cp dist.zip s3://dev-hobby
