name: ship-check-be-action
on:
  push:
    branches:
      - mainTest

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: dependencies
        run: npm install

      - name: test
        run: npm test
